version: '3.8'
services:
  frontend-react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
  backend-spring:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: spring-api
    volumes:
      - ./backend/src:/app/src
    secrets:
      - secrets.properties
    ports:
      - 8080:8080
      - 5005:5005
  react_native_app:
    build:
      context: ./mobile
      dockerfile: Dockerfile.dev
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./mobile:/app
    network_mode: "host"  # Use the host network mode
    healthcheck:
      disable: true
    
secrets:
  secrets.properties:
    file: ./backend/secrets.properties