version: '3.8'
services:
  frontend-react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
  backend-spring:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: spring-api
    volumes:
      - ./backend/src:/app/src
    secrets:
      - secrets.properties
    ports:
      - 8080:8080
      - 5005:5005
  mobile-native:
    build:
      context: ./mobile
      dockerfile: Dockerfile.dev
    container_name: mobile-native
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006
      - 3000:3000
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.25
    volumes:
      - ./mobile:/app
    
secrets:
  secrets.properties:
    file: ./backend/secrets.properties