version: '3.8'
services:
  frontend-react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend-spring:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: spring-api
    volumes:
      - ./backend/src:/app/src
    secrets:
      - secrets.properties
    ports:
      - 8080:8080
      - 5005:5005
    networks:
      - backend-network

  mongodb:
    image: mongo:jammy
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    profiles: [local-db]
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
volumes:
  mongodb-data:
secrets:
  secrets.properties:
    file: ./backend/secrets.properties