version: '3.8'
services:
  frontend-react:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
  backend-spring:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: spring-api
    volumes:
      - ./backend/src:/app/src
    secrets:
      - secrets.properties
    ports:
      - 8080:8080
      - 5005:5005
secrets:
  secrets.properties:
    file: ./backend/secrets.properties