version: '3.8'
services:
  frontend-react:
    build: ./frontend
    container_name: frontend-react
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
  backend-spring:
    build: ./backend
    container_name: spring-api
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8080:8080
      - 5005:5005