name: Build backend spring boot server
on:
  workflow_dispatch:
  #pull_request:
  #  branches: [ main ]
  #  types: closed
  #  paths:
  #    - 'backend/**'
env:
  working-directory: ./backend
  AWS_REGION: eu-central-1
  AWS_S3_BUCKET: rimatch-app
  MONGO_URI: ${{ secrets.MONGO_URI }}
jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with maven
        run: nvm clean install
        working-directory: ${{ env.working-directory }}